/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_admin_htsengine_JniHtsEngine */

#ifndef _Included_com_admin_htsengine_JniHtsEngine
#define _Included_com_admin_htsengine_JniHtsEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_admin_htsengine_JniHtsEngine
 * Method:    HtsEngine
 * Signature: (IC)I
 */
JNIEXPORT jint JNICALL Java_com_admin_htsengine_JniHtsEngine_HtsEngine
  (JNIEnv *, jobject, jint, jchar);

#ifdef __cplusplus
}
#endif
#endif
