/* DO NOT EDIT THIS FILE - it is machine generated */
#include <com_admin_jnidemo_JNITest.h>
/* Header for class com_jni_jnitest_JNITest */

/*
 * Class:     com_jni_jnitest_JNITest
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jint JNICALL Java_com_admin_jnidemo_JNITest_add
        (JNIEnv * env, jobject obj,  jint x, jint y){
    return x+y;
};


