/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_admin_bp_JniBp */

#ifndef _Included_com_admin_bp_JniBp
#define _Included_com_admin_bp_JniBp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_admin_bp_JniBp
 * Method:    Bp
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_admin_bp_JniBp_Bp
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
