/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_shengyi_jniadd_JNIAdd */

#ifndef _Included_com_shengyi_jniadd_JNIAdd
#define _Included_com_shengyi_jniadd_JNIAdd
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_shengyi_jniadd_JNIAdd
 * Method:    Add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_shengyi_jniadd_JNIAdd_Add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
